apiVersion: v1
kind: Service
metadata:
  name: {{ template "besu-monitoring.fullname" . }}-grafana
  labels:
    app: {{ template "besu-monitoring.name" . }}
    chart: {{ template "besu-monitoring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: monitoring
    component: grafana
  namespace: monitoring
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      name: grafana
  selector:
    component: grafana
  type: LoadBalancer
